//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameDummy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrameDummy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running
        ///{0}
        ///
        ///{1}.
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default icon).
        /// </summary>
        internal static string StringDefaultIcon {
            get {
                return ResourceManager.GetString("StringDefaultIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameDummy - Press Ctrl+S for settings.
        /// </summary>
        internal static string StringDefaultTitle {
            get {
                return ResourceManager.GetString("StringDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load icon from
        ///{0}
        ///
        ///This is not a valid icon file, or the file does not exist..
        /// </summary>
        internal static string StringIconFileLoadError {
            get {
                return ResourceManager.GetString("StringIconFileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Cannot load this image file. This is not a valid image file, or its format is not currently supported..
        /// </summary>
        internal static string StringImageFileLoadError {
            get {
                return ResourceManager.GetString("StringImageFileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load image from
        ///{0}
        ///
        ///The file does not exist..
        /// </summary>
        internal static string StringImageFileNotFoundError {
            get {
                return ResourceManager.GetString("StringImageFileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlBox.
        /// </summary>
        internal static string StringIniControlBox {
            get {
                return ResourceManager.GetString("StringIniControlBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to framedummy.ini.
        /// </summary>
        internal static string StringIniFileName {
            get {
                return ResourceManager.GetString("StringIniFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximized.
        /// </summary>
        internal static string StringIniMaximized {
            get {
                return ResourceManager.GetString("StringIniMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no image).
        /// </summary>
        internal static string StringNoImage {
            get {
                return ResourceManager.GetString("StringNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (pasted image).
        /// </summary>
        internal static string StringPastedImage {
            get {
                return ResourceManager.GetString("StringPastedImage", resourceCulture);
            }
        }
    }
}
